version: "3.9"

services:

  my_mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootirootroot
      MYSQL_DATABASE: superdb
      MYSQL_USER: hansi
      MYSQL_PASSWORD: datwirdschonsischersein123!
    ports:
      - "9906:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  my_php_server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-php
    depends_on:
      - my_mysql_db
    ports:
      - "8080:80"
